// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgsQHBIp-SvJlrF7LTHYq2rxkz4kj1c8M',
    appId: '1:210891886333:web:27276d3ee60e1e27423894',
    messagingSenderId: '210891886333',
    projectId: 'kitty-expense-managemen-elvbyq',
    authDomain: 'kitty-expense-managemen-elvbyq.firebaseapp.com',
    databaseURL: 'https://kitty-expense-managemen-elvbyq-default-rtdb.firebaseio.com',
    storageBucket: 'kitty-expense-managemen-elvbyq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4hQ0QpOQCDovO6FVH-FKEPEg-Kq1h1pQ',
    appId: '1:210891886333:android:e7dc851e5ca46627423894',
    messagingSenderId: '210891886333',
    projectId: 'kitty-expense-managemen-elvbyq',
    databaseURL: 'https://kitty-expense-managemen-elvbyq-default-rtdb.firebaseio.com',
    storageBucket: 'kitty-expense-managemen-elvbyq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCAodpvyaFIUDFUCEcpJOCiU0xUp92GYs',
    appId: '1:210891886333:ios:01c600e6c6a6f154423894',
    messagingSenderId: '210891886333',
    projectId: 'kitty-expense-managemen-elvbyq',
    databaseURL: 'https://kitty-expense-managemen-elvbyq-default-rtdb.firebaseio.com',
    storageBucket: 'kitty-expense-managemen-elvbyq.firebasestorage.app',
    androidClientId: '210891886333-h9a3pde2g8hig50t7p70lbhgci8naiet.apps.googleusercontent.com',
    iosBundleId: 'com.example.camalingo',
  );
}
